import {
  AppStore,
  Client,
  DataSource,
  FxRate,
  IdentityLink,
  NormalizedFact,
  RawSnapshot,
  ReportAnnotation,
  ReportVersion,
  ReviewException,
  User,
} from "../domain/model.js";
import { hashValue, normalizeEmail, normalizePhone } from "../domain/identity.js";
import { toReportingDate } from "../domain/time.js";

function rawSnapshot(source: string, sourceRecordKey: string): RawSnapshot {
  return {
    id: `snapshot-${source}-${sourceRecordKey}`,
    clientId: "client-bada-auto",
    source: source as RawSnapshot["source"],
    sourceRecordKey,
    capturedAt: new Date("2026-03-18T12:00:00.000Z").toISOString(),
    payload: { sourceRecordKey },
  };
}

function fact(input: Omit<NormalizedFact, "reportingDateLocal" | "syncedAt" | "rawSnapshotId">): NormalizedFact {
  return {
    ...input,
    reportingDateLocal: toReportingDate(input.occurredAtUtc, input.reportingTimezone),
    syncedAt: new Date("2026-03-18T12:00:00.000Z").toISOString(),
    rawSnapshotId: `snapshot-${input.source}-${input.sourceRecordKey}`,
  };
}

export function createSeedStore(): AppStore {
  const users: User[] = [
    { id: "user-admin", name: "Bada Admin", email: "ops@bada.digital" },
    { id: "user-editor", name: "Account Strategist", email: "client@bada.digital" },
  ];

  const client: Client = {
    id: "client-bada-auto",
    name: "Bada Auto Group",
    createdAt: new Date("2026-01-01T00:00:00.000Z").toISOString(),
    config: {
      leadDefinition: "A lead is a valid inbound form or call record accepted by the sales team.",
      newClientDefinition: "A new client is a Close opportunity that reaches won with a valid delivery date.",
      reportingTimezone: "America/New_York",
      reportingCurrency: "USD",
      spendBasis: "gross",
      pipelineMappings: {
        close_sales_pipeline: ["won", "contract_sent", "demo_complete"],
      },
      bookingMappings: {
        strategy_call: ["calendar:strategy"],
        triage_call: ["calendar:triage"],
      },
      revenueMappings: {
        booked: "close.opportunity_value",
        collected: "close.collected_cash",
      },
      duplicateRules: [
        "Exact normalized email wins when unique.",
        "Exact E.164 phone wins when unique.",
        "Ambiguous overlaps create exceptions instead of auto-merges.",
      ],
      manualImportSources: ["offline_call_center"],
      metricSourceRules: [
        { metricKey: "total_spend", sourcePriority: ["meta_ads", "manual_import"], fallbackToManualImport: true },
        { metricKey: "leads", sourcePriority: ["gohighlevel", "manual_import", "meta_ads"], fallbackToManualImport: true },
        { metricKey: "strategy_calls", sourcePriority: ["gohighlevel", "manual_import"], fallbackToManualImport: true },
        { metricKey: "triage_calls", sourcePriority: ["gohighlevel", "manual_import"], fallbackToManualImport: true },
        { metricKey: "new_clients", sourcePriority: ["close", "manual_import"], fallbackToManualImport: true },
        { metricKey: "new_revenue_booked", sourcePriority: ["close", "manual_import"], fallbackToManualImport: true },
        { metricKey: "new_revenue_collected", sourcePriority: ["close", "manual_import"], fallbackToManualImport: true },
      ],
    },
    metricTargets: {
      new_clients: 20,
      leads: 180,
      strategy_calls: 55,
      triage_calls: 38,
      total_spend: 13500,
      new_revenue_booked: 95000,
      new_revenue_collected: 76000,
    },
    metricOwners: {
      new_clients: "user-editor",
      total_spend: "user-admin",
      leads: "user-editor",
      strategy_calls: "user-editor",
    },
  };

  const dataSources: DataSource[] = [
    {
      id: "ds-meta",
      clientId: client.id,
      source: "meta_ads",
      displayName: "Meta Ads - CAD Account",
      accountCurrency: "CAD",
      credentialStatus: "healthy",
      secretRef: "secret/meta/client-bada-auto",
      expiresAt: null,
      lastRefreshAt: "2026-03-18T11:45:00.000Z",
      lastSyncedAt: "2026-03-18T11:50:00.000Z",
      lastSuccessAt: "2026-03-18T11:50:00.000Z",
      lastError: null,
      retryCount: 0,
      expectedMaxLagMinutes: 120,
      syncMode: "rolling_window",
      rollingWindowDays: 30,
      rateLimitPolicy: { requestsPerMinute: 180, burstLimit: 30, backoffBaseMs: 1000 },
      health: "healthy",
    },
    {
      id: "ds-ghl",
      clientId: client.id,
      source: "gohighlevel",
      displayName: "GoHighLevel - Sales Ops",
      accountCurrency: "USD",
      credentialStatus: "healthy",
      secretRef: "secret/ghl/client-bada-auto",
      expiresAt: null,
      lastRefreshAt: "2026-03-18T11:20:00.000Z",
      lastSyncedAt: "2026-03-18T11:48:00.000Z",
      lastSuccessAt: "2026-03-18T11:48:00.000Z",
      lastError: null,
      retryCount: 0,
      expectedMaxLagMinutes: 30,
      syncMode: "rolling_window",
      rollingWindowDays: 14,
      rateLimitPolicy: { requestsPerMinute: 120, burstLimit: 20, backoffBaseMs: 1000 },
      health: "healthy",
    },
    {
      id: "ds-close",
      clientId: client.id,
      source: "close",
      displayName: "Close CRM",
      accountCurrency: "USD",
      credentialStatus: "healthy",
      secretRef: "secret/close/client-bada-auto",
      expiresAt: null,
      lastRefreshAt: "2026-03-18T11:10:00.000Z",
      lastSyncedAt: "2026-03-18T11:55:00.000Z",
      lastSuccessAt: "2026-03-18T11:55:00.000Z",
      lastError: null,
      retryCount: 0,
      expectedMaxLagMinutes: 60,
      syncMode: "rolling_window",
      rollingWindowDays: 21,
      rateLimitPolicy: { requestsPerMinute: 120, burstLimit: 20, backoffBaseMs: 1000 },
      health: "healthy",
    },
  ];

  const fxRates: FxRate[] = [
    { id: "fx-2026-03-02", baseCurrency: "CAD", quoteCurrency: "USD", rate: 0.73, rateDate: "2026-03-02", source: "manual_seed" },
    { id: "fx-2026-03-05", baseCurrency: "CAD", quoteCurrency: "USD", rate: 0.731, rateDate: "2026-03-05", source: "manual_seed" },
    { id: "fx-2026-03-10", baseCurrency: "CAD", quoteCurrency: "USD", rate: 0.728, rateDate: "2026-03-10", source: "manual_seed" },
    { id: "fx-2026-03-12", baseCurrency: "CAD", quoteCurrency: "USD", rate: 0.727, rateDate: "2026-03-12", source: "manual_seed" },
    { id: "fx-2026-03-15", baseCurrency: "CAD", quoteCurrency: "USD", rate: 0.726, rateDate: "2026-03-15", source: "manual_seed" },
    { id: "fx-2026-02-27", baseCurrency: "CAD", quoteCurrency: "USD", rate: 0.724, rateDate: "2026-02-27", source: "manual_seed" }
  ];

  const rawSnapshots: RawSnapshot[] = [
    rawSnapshot("meta_ads", "meta-ad-a-spend-2026-03-02"),
    rawSnapshot("meta_ads", "meta-ad-b-spend-2026-03-05"),
    rawSnapshot("gohighlevel", "ghl-lead-a-2026-03-02"),
    rawSnapshot("gohighlevel", "ghl-call-a-2026-03-10"),
    rawSnapshot("close", "close-won-a-2026-03-15"),
    rawSnapshot("close", "close-collected-a-2026-03-15"),
    rawSnapshot("close", "close-won-feb-2026-02-27"),
  ];

  const commonDimensionsA = {
    campaignId: "cmp-1",
    campaignName: "Inventory Push",
    adsetId: "adset-1",
    adsetName: "Used Cars",
    adId: "ad-1",
    adName: "SUV Test Drive",
  };

  const commonDimensionsB = {
    campaignId: "cmp-2",
    campaignName: "Trade In",
    adsetId: "adset-2",
    adsetName: "Sedans",
    adId: "ad-2",
    adName: "Trade Up Today",
  };

  const facts: NormalizedFact[] = [
    fact({
      id: "fact-meta-spend-a-1",
      clientId: client.id,
      source: "meta_ads",
      sourceRecordKey: "meta-ad-a-spend-2026-03-02",
      factType: "ad_spend",
      occurredAtUtc: "2026-03-02T14:00:00.000Z",
      reportingTimezone: client.config.reportingTimezone,
      valueKind: "currency",
      value: 2200,
      amountNative: 2200,
      currencyNative: "CAD",
      dimensions: commonDimensionsA,
    }),
    fact({
      id: "fact-meta-spend-b-1",
      clientId: client.id,
      source: "meta_ads",
      sourceRecordKey: "meta-ad-b-spend-2026-03-05",
      factType: "ad_spend",
      occurredAtUtc: "2026-03-05T14:00:00.000Z",
      reportingTimezone: client.config.reportingTimezone,
      valueKind: "currency",
      value: 1900,
      amountNative: 1900,
      currencyNative: "CAD",
      dimensions: commonDimensionsB,
    }),
    fact({
      id: "fact-meta-impressions-a",
      clientId: client.id,
      source: "meta_ads",
      sourceRecordKey: "meta-ad-a-impressions-2026-03-02",
      factType: "impressions",
      occurredAtUtc: "2026-03-02T14:00:00.000Z",
      reportingTimezone: client.config.reportingTimezone,
      valueKind: "count",
      value: 44000,
      dimensions: commonDimensionsA,
    }),
    fact({
      id: "fact-meta-clicks-a",
      clientId: client.id,
      source: "meta_ads",
      sourceRecordKey: "meta-ad-a-clicks-2026-03-02",
      factType: "link_clicks",
      occurredAtUtc: "2026-03-02T14:00:00.000Z",
      reportingTimezone: client.config.reportingTimezone,
      valueKind: "count",
      value: 1320,
      dimensions: commonDimensionsA,
    }),
    fact({
      id: "fact-meta-leads-a",
      clientId: client.id,
      source: "meta_ads",
      sourceRecordKey: "meta-ad-a-leads-2026-03-02",
      factType: "lead",
      occurredAtUtc: "2026-03-02T14:00:00.000Z",
      reportingTimezone: client.config.reportingTimezone,
      valueKind: "count",
      value: 58,
      dimensions: commonDimensionsA,
    }),
    fact({
      id: "fact-meta-impressions-b",
      clientId: client.id,
      source: "meta_ads",
      sourceRecordKey: "meta-ad-b-impressions-2026-03-05",
      factType: "impressions",
      occurredAtUtc: "2026-03-05T14:00:00.000Z",
      reportingTimezone: client.config.reportingTimezone,
      valueKind: "count",
      value: 39500,
      dimensions: commonDimensionsB,
    }),
    fact({
      id: "fact-meta-clicks-b",
      clientId: client.id,
      source: "meta_ads",
      sourceRecordKey: "meta-ad-b-clicks-2026-03-05",
      factType: "link_clicks",
      occurredAtUtc: "2026-03-05T14:00:00.000Z",
      reportingTimezone: client.config.reportingTimezone,
      valueKind: "count",
      value: 1040,
      dimensions: commonDimensionsB,
    }),
    fact({
      id: "fact-meta-leads-b",
      clientId: client.id,
      source: "meta_ads",
      sourceRecordKey: "meta-ad-b-leads-2026-03-05",
      factType: "lead",
      occurredAtUtc: "2026-03-05T14:00:00.000Z",
      reportingTimezone: client.config.reportingTimezone,
      valueKind: "count",
      value: 44,
      dimensions: commonDimensionsB,
    }),
    fact({
      id: "fact-ghl-leads-a",
      clientId: client.id,
      source: "gohighlevel",
      sourceRecordKey: "ghl-lead-a-2026-03-02",
      factType: "lead",
      occurredAtUtc: "2026-03-02T23:45:00.000Z",
      reportingTimezone: client.config.reportingTimezone,
      valueKind: "count",
      value: 52,
      dimensions: {
        ...commonDimensionsA,
        formId: "form-1",
        formName: "SUV Lead Form",
        contactKey: "contact-a",
      },
    }),
    fact({
      id: "fact-ghl-strategy-a",
      clientId: client.id,
      source: "gohighlevel",
      sourceRecordKey: "ghl-call-a-2026-03-10",
      factType: "strategy_call",
      occurredAtUtc: "2026-03-10T15:00:00.000Z",
      reportingTimezone: client.config.reportingTimezone,
      valueKind: "count",
      value: 18,
      dimensions: {
        ...commonDimensionsA,
        calendarId: "calendar-strategy",
        calendarName: "Strategy Calendar",
      },
    }),
    fact({
      id: "fact-ghl-triage-a",
      clientId: client.id,
      source: "gohighlevel",
      sourceRecordKey: "ghl-triage-a-2026-03-12",
      factType: "triage_call",
      occurredAtUtc: "2026-03-12T16:00:00.000Z",
      reportingTimezone: client.config.reportingTimezone,
      valueKind: "count",
      value: 12,
      dimensions: {
        ...commonDimensionsA,
        calendarId: "calendar-triage",
        calendarName: "Triage Calendar",
      },
    }),
    fact({
      id: "fact-ghl-leads-b",
      clientId: client.id,
      source: "gohighlevel",
      sourceRecordKey: "ghl-lead-b-2026-03-05",
      factType: "lead",
      occurredAtUtc: "2026-03-05T18:00:00.000Z",
      reportingTimezone: client.config.reportingTimezone,
      valueKind: "count",
      value: 40,
      dimensions: {
        ...commonDimensionsB,
        formId: "form-2",
        formName: "Trade In Form",
        contactKey: "contact-b",
      },
    }),
    fact({
      id: "fact-ghl-strategy-b",
      clientId: client.id,
      source: "gohighlevel",
      sourceRecordKey: "ghl-call-b-2026-03-10",
      factType: "strategy_call",
      occurredAtUtc: "2026-03-10T18:00:00.000Z",
      reportingTimezone: client.config.reportingTimezone,
      valueKind: "count",
      value: 15,
      dimensions: {
        ...commonDimensionsB,
        calendarId: "calendar-strategy",
        calendarName: "Strategy Calendar",
      },
    }),
    fact({
      id: "fact-ghl-triage-b",
      clientId: client.id,
      source: "gohighlevel",
      sourceRecordKey: "ghl-triage-b-2026-03-12",
      factType: "triage_call",
      occurredAtUtc: "2026-03-12T19:00:00.000Z",
      reportingTimezone: client.config.reportingTimezone,
      valueKind: "count",
      value: 10,
      dimensions: {
        ...commonDimensionsB,
        calendarId: "calendar-triage",
        calendarName: "Triage Calendar",
      },
    }),
    fact({
      id: "fact-close-new-client-a",
      clientId: client.id,
      source: "close",
      sourceRecordKey: "close-won-a-2026-03-15",
      factType: "new_client",
      occurredAtUtc: "2026-03-15T18:00:00.000Z",
      reportingTimezone: client.config.reportingTimezone,
      valueKind: "count",
      value: 7,
      dimensions: {
        ...commonDimensionsA,
        pipelineId: "pipeline-close",
        pipelineName: "Sales Pipeline",
        stageId: "won",
        stageName: "Won",
        opportunityId: "opp-a",
      },
    }),
    fact({
      id: "fact-close-booked-a",
      clientId: client.id,
      source: "close",
      sourceRecordKey: "close-booked-a-2026-03-15",
      factType: "revenue_booked",
      occurredAtUtc: "2026-03-15T18:00:00.000Z",
      reportingTimezone: client.config.reportingTimezone,
      valueKind: "currency",
      value: 28000,
      amountNative: 28000,
      currencyNative: "USD",
      dimensions: {
        ...commonDimensionsA,
        pipelineId: "pipeline-close",
        stageId: "won",
        opportunityId: "opp-a",
      },
    }),
    fact({
      id: "fact-close-collected-a",
      clientId: client.id,
      source: "close",
      sourceRecordKey: "close-collected-a-2026-03-15",
      factType: "revenue_collected",
      occurredAtUtc: "2026-03-15T18:00:00.000Z",
      reportingTimezone: client.config.reportingTimezone,
      valueKind: "currency",
      value: 19000,
      amountNative: 19000,
      currencyNative: "USD",
      dimensions: {
        ...commonDimensionsA,
        pipelineId: "pipeline-close",
        stageId: "won",
        opportunityId: "opp-a",
      },
    }),
    fact({
      id: "fact-close-new-client-b",
      clientId: client.id,
      source: "close",
      sourceRecordKey: "close-won-b-2026-03-15",
      factType: "new_client",
      occurredAtUtc: "2026-03-15T19:00:00.000Z",
      reportingTimezone: client.config.reportingTimezone,
      valueKind: "count",
      value: 5,
      dimensions: {
        ...commonDimensionsB,
        pipelineId: "pipeline-close",
        pipelineName: "Sales Pipeline",
        stageId: "won",
        stageName: "Won",
        opportunityId: "opp-b",
      },
    }),
    fact({
      id: "fact-close-booked-b",
      clientId: client.id,
      source: "close",
      sourceRecordKey: "close-booked-b-2026-03-15",
      factType: "revenue_booked",
      occurredAtUtc: "2026-03-15T19:00:00.000Z",
      reportingTimezone: client.config.reportingTimezone,
      valueKind: "currency",
      value: 22500,
      amountNative: 22500,
      currencyNative: "USD",
      dimensions: {
        ...commonDimensionsB,
        pipelineId: "pipeline-close",
        stageId: "won",
        opportunityId: "opp-b",
      },
    }),
    fact({
      id: "fact-close-collected-b",
      clientId: client.id,
      source: "close",
      sourceRecordKey: "close-collected-b-2026-03-15",
      factType: "revenue_collected",
      occurredAtUtc: "2026-03-15T19:00:00.000Z",
      reportingTimezone: client.config.reportingTimezone,
      valueKind: "currency",
      value: 14500,
      amountNative: 14500,
      currencyNative: "USD",
      dimensions: {
        ...commonDimensionsB,
        pipelineId: "pipeline-close",
        stageId: "won",
        opportunityId: "opp-b",
      },
    }),
    fact({
      id: "fact-close-feb-collected",
      clientId: client.id,
      source: "close",
      sourceRecordKey: "close-collected-feb-2026-02-27",
      factType: "revenue_collected",
      occurredAtUtc: "2026-02-27T20:00:00.000Z",
      reportingTimezone: client.config.reportingTimezone,
      valueKind: "currency",
      value: 11000,
      amountNative: 11000,
      currencyNative: "USD",
      dimensions: {
        ...commonDimensionsA,
        pipelineId: "pipeline-close",
        stageId: "won",
        opportunityId: "opp-feb",
      },
    }),
  ];

  const identityLinks: IdentityLink[] = [
    {
      id: "link-a",
      clientId: client.id,
      contactKey: "contact-a",
      normalizedEmailHash: hashValue(normalizeEmail("lead-a@example.com")),
      normalizedPhoneHash: hashValue(normalizePhone("+1 (555) 111-2222")),
      metaLeadKey: "meta-lead-a",
      ghlContactKey: "ghl-contact-a",
      closeLeadKey: "close-lead-a",
    },
    {
      id: "link-b",
      clientId: client.id,
      contactKey: "contact-b",
      normalizedEmailHash: hashValue(normalizeEmail("lead-b@example.com")),
      normalizedPhoneHash: hashValue(normalizePhone("+1 (555) 333-4444")),
      metaLeadKey: "meta-lead-b",
      ghlContactKey: "ghl-contact-b",
      closeLeadKey: "close-lead-b",
    },
  ];

  const annotations: ReportAnnotation[] = [
    {
      clientId: client.id,
      reportMonth: "2026-03",
      metricKey: "new_clients",
      status: "green",
      ownerUserId: "user-editor",
      sourceNote: "Close is the authority for won deals.",
      riskNote: null,
      manualOverrideValue: null,
      overrideReason: null,
      updatedBy: "user-editor",
      updatedAt: "2026-03-18T09:00:00.000Z",
    },
    {
      clientId: client.id,
      reportMonth: "2026-03",
      metricKey: "leads",
      status: "yellow",
      ownerUserId: "user-editor",
      sourceNote: "GHL leads are lower than Meta native leads because duplicate/unqualified records are filtered.",
      riskNote: "Sales team still reconciling two offline leads.",
      manualOverrideValue: null,
      overrideReason: null,
      updatedBy: "user-editor",
      updatedAt: "2026-03-18T09:10:00.000Z",
    },
  ];

  const reportVersions: ReportVersion[] = [
    {
      id: "rv-client-bada-auto-2026-02-1",
      clientId: client.id,
      reportMonth: "2026-02",
      lockedAt: "2026-03-01T14:00:00.000Z",
      lockedBy: "user-admin",
      versionNumber: 1,
      snapshot: [
        {
          metricKey: "new_revenue_collected",
          value: 9500,
          status: "green",
          ownerUserId: "user-admin",
          sourceNote: "Close published at month close.",
          riskNote: null,
        },
      ],
    },
  ];

  const exceptions: ReviewException[] = [
    {
      id: "ex-leads-variance",
      clientId: client.id,
      reportMonth: "2026-03",
      type: "conflicting_source_totals",
      status: "open",
      title: "Lead totals differ between Meta and GoHighLevel",
      detail: "Meta native leads are higher than GHL accepted leads. Review duplicate and qualification filters.",
      metricKey: "leads",
      relatedSource: "gohighlevel",
      createdAt: "2026-03-18T09:05:00.000Z",
      updatedAt: "2026-03-18T09:05:00.000Z",
    },
  ];

  return {
    users,
    memberships: [
      { clientId: client.id, userId: "user-admin", role: "agency_admin" },
      { clientId: client.id, userId: "user-editor", role: "client_editor" },
    ],
    clients: [client],
    dataSources,
    fxRates,
    rawSnapshots,
    facts,
    identityLinks,
    annotations,
    reportVersions,
    exceptions,
  };
}
